### ISSUE TITLE
Athena query timeout - 504

### ISSUE THREAD

**Issue by katebrenner** [grafana/athena-datasource#319]
**What happened**:
Users are reporting experiencing slow Athena dashboard loading, on the first loading. "After 5-10 minutes of manual reloads and several 504 Gateway Timeout errors, we finally get all our dashboards working fine for the rest of the day." (https://github.com/grafana/grafana/issues/71946#issuecomment-1968494233) and https://github.com/grafana/athena-datasource/issues/99#issuecomment-1866744050

**What you expected to happen**:
Not this........

**Comment by dcram** [comment]
Thank you for reporting this here @katebrenner.

We are still experiencing the issue.

**Comment by iwysiu** [comment]
Hi @dcram ! I investigated this, and it seems like a lot of this is related to Athena behavior. The “HTTP 504 Gateway Timeout” comes from AWS's load balancing and I found these docs from AMG about resolving it: https://repost.aws/knowledge-center/grafana-504-timeout-vpc. There is also information about how to tune Athena data and queries to improve the response time https://docs.aws.amazon.com/athena/latest/ug/performance-tuning.html. My understand of the docs is that when the queries are initially run, [Athena needs to assign resources](https://docs.aws.amazon.com/athena/latest/ug/performance-tuning.html), which is why they’re slow for the first query, but improve afterwards.
I can look into retrying on the Gateway Timeout, but that won’t fix the underlying issue of the queries initially taking a long time.

**Comment by aligthart** [comment]
We experience something similar but not sure if the links mentioned above describe the issue.
For us it depends on what authentication mechanism we use.

Our setup.
Grafana deployed as part of prometheus stack on a kubernetes cluster that is setup with Kops. IAM-role on the workers with a policy to access athena\S3 in another AWS account.

Below part of our helm chart to configure the above
```
grafana:
  plugins:
    - grafana-athena-datasource
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Athena
          type: grafana-athena-datasource
          jsonData:
            authType: ec2_iam_role
            assumeRoleArn: arn:aws:iam::xxxxxxxxxxxxxx:role/yyyyyyyyyyyy
            defaultRegion: eu-west-1
            catalog: AwsDataCatalog
            database: 'ourdatabase'
            workgroup: 'primary'
            outputLocation: s3://aws-athena-query-results-xxxxxxxxxxxxxxx-eu-west-1/ourlocation
  "grafana.ini":
    aws:
      allowed_auth_providers: default,keys,credentials,ec2_iam_role
```

* with the above setup we also experience these gateway timeout that magically disappear after 5 a few minutes. Not sure what makes it work.
* when changing the authentication provider from "ec2_iam_role" to "keys" then all works fine instantly. The datasource instantly starts returning results from the athena in the other AWS account

When creating a datasource manually in Grafana it always works with (access and secret) keys. But when manually creation a datasource using the workspace IAM role (ec2_iam_role provider) it is impossible to get it working. Looks like this timeout issue is worsened by the order in which values are entered.

So only when creating via automation the iam_role works but with this timeout issue. 
No issues at all when using the keys provider.
